### PR TITLE
Proposed baseline u-boot branch

### PR DESCRIPTION
**Pull request by sarnold**
Note this goes on top of u-boot 2021.04  (this PR is strictly for viewing/testing purposes)

### CODE REVIEW

**Comment by xypron** [comment]
We should not accept patches without a commit message which explains why the change is done.

**Comment by pdp7** [comment]
@xypron the point of this PR was to [properly rebase the starfive patches on top of u-boot](https://github.com/starfive-tech/u-boot/issues/13#issuecomment-847352566).   @sarnold is proposing that be done on top of https://github.com/u-boot/u-boot/commit/b46dd116ce03e235f2a7d4843c6278e1da44b5e1

It is true that all the patches from @tekkamanninja and the StarFive team need to be refactored into a logical series of changes with proper signed-off-by, but that is outside of the context of this PR.

**Comment by lbmeng** [comment]
> It is true that all the patches from @tekkamanninja and the StarFive team need to be refactored into a logical series of changes with proper signed-off-by, but that is outside of the context of this PR.

Correct. This PR is for the StarFive downstream repo. It is clear that lots of refactor are needed before them can go upstream.

**Comment by pdp7** [comment]
@sarnold I created this issue to ask @tekkamanninja or @MichaelZhuxx to clean up the branches:
https://github.com/starfive-tech/u-boot/issues/15

@tekkamanninja did point out to me when I talked to him tonight that `Fedora_VIC_7100_2021.04` does already contain https://github.com/starfive-tech/u-boot/commit/b46dd116ce03e235f2a7d4843c6278e1da44b5e1 `("Prepare v2021.04")`

https://github.com/starfive-tech/u-boot/commits/Fedora_VIC_7100_2021.04?after=7b70e1d44ba9702a519ca936cabf19070309123a+34&branch=Fedora_VIC_7100_2021.04

**Comment by sarnold** [comment]
yes, https://github.com/starfive-tech/u-boot/commit/b46dd116ce03e235f2a7d4843c6278e1da44b5e1 ("Prepare v2021.04") is the base commit that beaglev commits should start from (at least if you want to stay on v2021.04).

**Comment by pdp7** [comment]
closing now that @tekkamanninja as has rebased on 2021.07 https://github.com/starfive-tech/u-boot/tree/Fedora_JH7100_upstream

**Pull request closed without merging**
