### PR TITLE
Enabling full 2M L2 cache

### PR DESCRIPTION
**Pull request by mcd500**
Enabling full 2M L2 cache. Improve the performance.

These patches are cleanup from @davidlt.
https://github.com/davidlt/u-boot/tree/Fedora

### CODE REVIEW

**Comment by davidlt** [comment]
LGTM

**Review by davidlt — APPROVED** [review]

**Review by lbmeng — CHANGES_REQUESTED** [review]
This commit should be "git revert 7b70e1d44ba9702a519ca936cabf19070309123a"

**Comment by davidlt** [comment]
True (and more). When I wrote it I wanted to have minimal changes to existing code base. In general I don't see a need for `CONFIG_SIFIVE_FU540_L2CC_WAYENABLE_DIY` or `CONFIG_SIFIVE_FU540_L2CC_WAYENABLE_DIY_NUM` and the corresponding code. This could go away too: https://github.com/starfive-tech/u-boot/commit/2232385e6f97bb320e058748dd4336a15fbc9ad2

I think better enable full L2 now and later clean up the rest.

**Comment by lbmeng** [comment]
> I think better enable full L2 now and later clean up the rest.

As of now the starfive-tech/u-boot is the downstream mainline for BeagleV, IMHO we'd better follow some sort of process so that when we clean up the patches for upstream we know which commit is not necessary. Maybe I am too nitpicking here :)

So yes, better to revert 2232385e6f97bb320e058748dd4336a15fbc9ad2 as well.

**Comment by pdp7** [comment]
@davidlt @lbmeng @mcd500 @tekkamanninja  I am updating the [beaglev_defconfig](https://github.com/buildroot/buildroot/blob/master/configs/beaglev_defconfig) in upstream buildroot to point to the newer versions of kernel and u-boot.  Currently my buildroot patch pointing is to HEAD of [Fedora_VIC_7100_2021.04](https://github.com/starfive-tech/u-boot/commits/Fedora_VIC_7100_2021.04): https://github.com/starfive-tech/u-boot/commit/abb06422a5cde46ef63ac23851f296b80ca6ad57

Is it possible to the commit(s) need to enable L2 cache into the Fedora_VIC_7100_2021.04 branch?  

I would like to make ensure buildroot is making full use of the L2 cache.

**Review by lbmeng — APPROVED** [review]

**Comment by lbmeng** [comment]
Let's do less churn, so I will merge this PR, and do a "git revert 2232385e6f97bb320e058748dd4336a15fbc9ad2" separately.

**Comment by mcd500** [comment]
@lbmeng @davidlt @pdp7 Thanks for merging. Now full 2M L2 cache and boot hang fix are included. Only 0x7c1 CSR is left and probably going into ddrinit.

**Pull request merged**
