### PR TITLE
Update StarFive U-Boot to work with upstream OpenSBI generic platform

### PR DESCRIPTION
**Pull request by lbmeng**
This addresses https://github.com/starfive-tech/opensbi/issues/4

Tested with:
- OpenSBI commit 54d7def6c254 ("lib: utils: Try other FDT drivers when we see SBI_ENODEV")
- dtb built from StarFive U-Boot repo

### CODE REVIEW

**Comment by esmil** [comment]
I've installed this (built by @atishp04) on my board and so far I haven't  seen the issue in https://github.com/starfive-tech/linux/issues/15 even though OpenSBI has choosen both hart 0 and hart 1 as boot hart.

@lbmeng Thanks!

**Comment by lbmeng** [comment]
Thanks @esmil for the confirmation. @pdp7 I am going to merge this. Do you see any problems?

**Comment by pdp7** [comment]
@tekkamanninja can we merge this?

**Comment by lbmeng** [comment]
I seem to have the privilege to click the button so if everyone agrees, I can do the merge.

**Comment by lbmeng** [comment]
Based on test results from @kraj, @esmil and @mcd500, I will merge this PR now.

**Pull request merged**
