### PR TITLE
VisionFive boot fixes

### PR DESCRIPTION
**Pull request by zorun**
* configs: starfive: define addresses according to Generic Distro spec
* starfive: enable BOOTCOMMAND so that DISTRO_DEFAULTS becomes useful
* configs: starfive: Change boot order to try DHCP last

See individual commit messages for details

### CODE REVIEW

**Comment by zorun** [comment]
I have successfully tested these patches on a VisionFive V1 board, and I could boot Debian without needing any uEnv.txt file.

**Comment by zorun** [comment]
Any update on this?

**Comment by zorun** [comment]
Just to clarify: the current u-boot on VisionFive v1 makes it hard for distros to support the board. And updating u-boot on a board is not something that most users will feel comfortable doing (btw, updating u-boot was well documented before, but I can't find the documentation on rvspace.org anymore :/).

So, it would be very helpful for the changes here to be integrated and shipped with the VisionFive V2 boards!

**Comment by orangecms** [comment]
For reference: The quick start guide has the instructions for upgrading U-Boot, recovery, etc..:
https://doc-en.rvspace.org/Doc_Center/quick_start_guide_visionfive.html

**Comment by orangecms** [comment]
I have an [oreboot port in the makings](https://github.com/oreboot/oreboot/pull/606) instead, which would only need one single binary eventually for the whole procedure - clocks/GPIOs/DRAM init, SBI, loading a payload - plus your custom app, e.g., bare metal, [LinuxBoot](https://linuxboot.org), hypervisor, whatever you like. :)

**Pull request merged**
